### ISSUE TITLE
hash<hashes::sha2<256>> is (likely?) broken

### ISSUE THREAD

**Issue by color-typea** [NilFoundation/zkLLVM#322]
**Steps to reproduce:** 

Create and register new example:
* create `examples/cpp/min_repro.cpp` (see below) and `examples/inputs/min_repro.inp` (just empty input: `[]`)
* Add to `examples/cpp/CMakeLists.txt` the following: `add_example_with_proving(min_repro SOURCES min_repro.cpp INPUT min_repro.inp)`
* (re)generate build (as instructed in https://docs.nil.foundation/zkllvm/starting-first-project/installation)

Circuit:

```
#include <nil/crypto3/hash/algorithm/hash.hpp>
#include <nil/crypto3/hash/sha2.hpp>
#include <cstdint>

using namespace nil::crypto3;

using hash_type = hashes::sha2<256>;
using block_type = hash_type::block_type;

bool is_same(block_type block0, block_type block1){
    return block0[0] == block1[0] && block0[1] == block1[1];
}

[[circuit]] void check_hash() {
    block_type a = { 0x01000000000000000000000000000000_cppui255, 0x00000000000000000000000000000000_cppui255 };
    block_type b = { 0x02000000000000000000000000000000_cppui255, 0x00000000000000000000000000000000_cppui255 };
    block_type hashed = { 0xff55c97976a840b4ced964ed49e37945_cppui255, 0x94ba3f675238b5fd25d282b60f70a194_cppui255 };
    block_type actual_hash = hash<hash_type>(a, b);
    bool equal = is_same(actual_hash, hashed);
    __builtin_assigner_exit_check(equal);
}
```

Run proving: `make -C ${ZKLLVM_BUILD:-build} min_repro_prove -j$(nproc)`

**Expected result:** Proof is generated and verified by the transpiler
**Actual result:** Transpiler fails during verification:

```
Preprocessing public data...
Preprocessing private data...
Generating proof...
Proof generated
Verifying proof...
Assertion failed at /home/john/Projects/crypto/zkllvm/zkllvm/bin/transpiler/src/main.cpp:460:
        verification_result -> Proof is not verified
Aborted (core dumped)
```

**Additional info:**
In the example above, we're essentially checking that sha2<256>(a, b) == expected_value. Here's how it behaves under different a and b:

* [Works] `a = 0, b = 0, hash = f5a5fd42d16a20302798ef6ed309979b43003d2320d9f0e8ea9831a92759fb4b`
* [Works] `a = 1, b = 0, hash = 16abab341fb7f370e27e4dadcf81766dd0dfd0ae64469477bb2cf6614938b2af`
* [Works] `a = 255 + (255 << 16 * 8), b = 0, hash = 7509c974164b248d5094a8adb4d1bd6a4641969693f650658160c08f028527bf`
* [Fails] `a = 0, b = 1, hash = cb592844121d926f1ca3ad4e1d6fb9d8e260ed6e3216361f7732e975a0e8bbf6`
* [Fails] `a = 0, b = 255, hash = e3345971e420209d5618401e6aea5b146c9705f8dc37ca54721ac66b4b780601`

... or, in other terms, works as expected as long as `b` is zero, fails if b is non-zero

**Toolchain versions:**
* Compiler: clang version 16.0.0 (git@github.com:NilFoundation/zkllvm-circifier.git c82f3c6343b09bca996134144762727057f5c697)
* Assigner: 0.1.4 (built from source on a4d5ee58ce2884f4c71da55c7228c1ef16d64e66)
* Transpiler: 0.1.4 (built from source on a4d5ee58ce2884f4c71da55c7228c1ef16d64e66)

**Appendix:**

Python code to generate a, b and hashed:

```
from hashlib import sha256

def block_type(value: bytes):
    return f"{{ 0x{value.hex()[:32]}_cppui255, 0x{value.hex()[32:]}_cppui255 }}"

def uint_to_bytes(value, size=32) -> bytes:
    return value.to_bytes(size, 'little', signed=False)

a, b = 1, 2
a_bytes, b_bytes = uint_to_bytes(a, 32), uint_to_bytes(b, 32)
hashed = hash_pair(a_bytes, b_bytes)

print(f"block_type a = {block_type(a_bytes)};")
print(f"block_type b = {block_type(b_bytes)};")
print(f"block_type hashed = {block_type(hashed)};")
```

**Comment by color-typea** [comment]
Bump - still does not work end-to-end on 5f2b7a3, but the error now happens during verification:

```
     Error: VM Exception while processing transaction: reverted with reason string 'update_transcript_b32_by_offset: offset < blob.length'
      at modular_verifier_playground.update_transcript_b32_by_offset_calldata (@nilfoundation/evm-placeholder-verification/contracts/cryptography/transcript.sol:60)
      at modular_verifier_playground.verify (contracts/gates/modular_verifier.sol:153)
      at generic_verification_contract.submitReportData (contracts/GenericContract.sol:21)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async HardhatNode.runCall (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:679:20)
      at async EthModule._callAction (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:360:9)
      at async HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:124:18)
      at async staticCallResult (node_modules/ethers/src.ts/contract/contract.ts:323:22)
      at async staticCall (node_modules/ethers/src.ts/contract/contract.ts:289:24)
      at async Proxy.submitReportData (node_modules/ethers/src.ts/contract/contract.ts:337:41)
```

Toolchain versions:
* Compiler: clang version 16.0.0 (git@github.com:NilFoundation/zkllvm-circifier.git 1b5d1ccdb41cfac9eeb64efe275f23054ffa2ed9)
* Transpiler, assigner: built from source at 5f2b7a3, 0.1.9-8
* evm-placeholder-verification: 1.1.2 ([package](https://github.com/NilFoundation/evm-placeholder-verification/pkgs/npm/evm-placeholder-verification/146653925))

Transpiler results: https://gist.github.com/color-typea/7b0a216fa0765d013c5318c29b540a59
